# PYNQ 2.1 METADATA ADAPTER ONLY -- NOT A VIVADO REBUILD SCRIPT.
# PYNQ reads these lines; do not execute this file in Vivado.
# Exact same-build Vivado export: maxcut26_epix_lfsr26_100mhz.vivado.tcl
# Derived from matching maxcut26_epix_lfsr26_100mhz.hwh SHA-256: 39ddefdb42940b342aaa4cd696fbd5e845eced6d713e1673372e5838646e3bca
# Generated by scripts/export_legacy_tcl.py; no RTL or bitstream changes.
create_project -part xc7z020clg400-1 solver_metadata .
set ps7_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7_0 ]
set maxcut26_0 [ create_bd_cell -type ip -vlnv date2027.local:user:maxcut26_axi:1.0 maxcut26_0 ]
set_property -dict [list
  CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR0 {5} \
  CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR1 {2} \
  CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
  CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR0 {1} \
  CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR1 {1} \
  CONFIG.PCW_FPGA_FCLK1_ENABLE {0} \
  CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR0 {1} \
  CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR1 {1} \
  CONFIG.PCW_FPGA_FCLK2_ENABLE {0} \
  CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR0 {1} \
  CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR1 {1} \
  CONFIG.PCW_FPGA_FCLK3_ENABLE {0} \
] $ps7_0
create_bd_addr_seg -range 0x00001000 -offset 0x43C00000 [get_bd_addr_spaces ps7_0/Data] [get_bd_addr_segs maxcut26_0/S_AXI/reg0] SEG_maxcut26
