#!/usr/bin/env python3
"""Generate frozen-clause and exact quantized native-weight ROMs and core copies."""
from __future__ import annotations
import argparse
import collections
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent


def load_cnf(path):
    clauses, pending, n = [], [], None
    for line in path.read_text().splitlines():
        if not line or line.startswith("c"):
            continue
        if line.startswith("p"):
            _, kind, n, count = line.split()
            assert kind == "cnf"
            n, count = int(n), int(count)
            continue
        for word in line.split():
            lit = int(word)
            if lit:
                pending.append(lit)
            else:
                assert len(pending) == 3 and len(set(map(abs, pending))) == 3
                clauses.append(pending)
                pending = []
    assert not pending and n in (32, 128, 288, 512, 800) and len(clauses) == count
    assert all(1 <= abs(v) <= n for row in clauses for v in row)
    return n, clauses


def quantize(breaks):
    # Evaluation order deliberately matches conditioned.h and initPoly().
    p = [math.pow(0.9 + b, -2.06) for b in breaks]
    total = p[0] + p[1] + p[2]
    x = [65533 * v / total for v in p]
    w = [1 + math.floor(v) for v in x]
    fraction = [v - math.floor(v) for v in x]
    while sum(w) < 65536:
        best = max(range(3), key=lambda j: (fraction[j], -j))
        w[best] += 1
        fraction[best] = -1
    assert all(v > 0 for v in w) and sum(w) == 65536
    return w


def artifacts(case):
    path = ROOT / "cases" / case
    n, clauses = load_cnf(path / "input.cnf")
    variable_width = (n-1).bit_length()
    literal_width = variable_width+1
    clause_width = 3*literal_width
    core = (HERE / "categorical_solver_sized.sv.in").read_text().replace("@VARIABLES@",str(n))
    occurrences = collections.Counter(v for row in clauses for v in row)
    maximum = max(occurrences.values())
    assert maximum < 256 and len(clauses) < 65536
    base = maximum + 1
    masses = [quantize([b0, b1, b2]) for b0 in range(base)
              for b1 in range(base) for b2 in range(base)]
    index_width = (base**3 - 1).bit_length()
    lines = ["// Generated by rtl/categorical/sized_generate.py; do not edit.",
             f"localparam integer CLAUSES={len(clauses)};",
             f"localparam integer MAX_BREAK={maximum};",
             f"function automatic [{clause_width-1}:0] clause_rom(input logic [15:0] index);",
             "    begin case(index)"]
    for index, row in enumerate(clauses):
        packed = sum(((abs(v) - 1) | ((1 << variable_width) if v > 0 else 0)) << (literal_width * j)
                     for j, v in enumerate(row))
        lines.append(f"        16'd{index}: clause_rom={clause_width}'h{packed:0{(clause_width+3)//4}x};")
    lines.extend([f"        default: clause_rom={clause_width}'d0;", "    endcase end", "endfunction",
                  "function automatic [33:0] mass_rom(input logic [7:0] b0,b1,b2);",
                  f"    reg [{index_width-1}:0] index;", "    begin",
                  f"        index={index_width}'((32'(b0)*{base}+32'(b1))*{base}+32'(b2));", "        case(index)"])
    for index, row in enumerate(masses):
        packed = row[0] | (row[1] << 17)
        lines.append(f"            {index_width}'d{index}: mass_rom=34'h{packed:09x};")
    lines.extend(["            default: mass_rom={17'd21845,17'd21846};",
                  "        endcase", "    end", "endfunction", ""])
    table = {"schema": "categorical_native_mass_rom_v1", "case": case,
             "break_max": maximum, "index": "(break0*(break_max+1)+break1)*(break_max+1)+break2",
             "weight": "pow(0.9+break,-2.06)", "quantization": "conditioned.h positive 16-bit masses; sum65536",
             "masses": masses}
    generated = {"rtl/weights.json": json.dumps(table, indent=2)+"\n"}
    for mode in ("baseline", "epix"):
        generated[f"rtl/{mode}/solver.sv"] = core
        generated[f"rtl/{mode}/clock_gate_sim.sv"] = (HERE / "clock_gate_sim.sv").read_text()
        generated[f"rtl/{mode}/instance.svh"] = "\n".join(lines)
    manifest = {
        "schema": "categorical_rtl_binding_v1", "case": case,
        "input_cnf_sha256": hashlib.sha256((path / "input.cnf").read_bytes()).hexdigest(),
        "core_sha256": hashlib.sha256(core.encode()).hexdigest(),
        "clauses": len(clauses), "variables": n, "maximum_break": maximum,
        "mass_table_rows": len(masses), "rng": "xorshift32(13,17,5), advance then output state>>1; zero seed maps1",
        "cache_value_bits": 47, "cache_range_bits": 47, "cache_age_bits": 8,
        "epix_age_limit": 254, "epix_relax": 1,
        "expected_icg_count": {"baseline": 1, "epix": len(clauses)+1},
        "files": {name: hashlib.sha256(data.encode()).hexdigest() for name,data in generated.items()}}
    generated["rtl/manifest.json"] = json.dumps(manifest, indent=2)+"\n"
    return path, generated


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--case", default="all")
    args = parser.parse_args()
    cases = [f"{family}{n}" for family in ("sat", "xorsat") for n in (32,288,512,800)]
    if args.case != "all":
        assert args.case in cases
        cases = [args.case]
    for case in cases:
        path, generated = artifacts(case)
        for name, text in generated.items():
            dest = path / name
            if args.check:
                assert dest.read_text() == text, f"stale generated artifact: {dest}"
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(text)
        print(f"{case}: {'verified' if args.check else 'generated'} {len(generated)} artifacts")


if __name__ == "__main__":
    main()
