#!/usr/bin/env python3
"""Generate graph and probability constants; no random trajectory is compiled."""
import json
from pathlib import Path
from reference import EDGES, GRAPH, LUT
ROOT=Path(__file__).resolve().parent

def generate():
    lines=['// Generated by generate_rtl.py from graph.json and the native probability definition.']
    lines += ['function automatic signed [5:0] raw_field(input integer node, input logic [127:0] state);', 'begin', 'case(node)']
    for i in range(128):
        terms=[]
        for u,v,w in EDGES:
            if i in (u,v):
                j=v if i==u else u
                terms.append(f'(state[{j}] ? ({-w}) : ({w}))')
        lines.append(f'{i}: raw_field=' + (' + '.join(terms) if terms else '0') + ';')
    lines += ['default: raw_field=0;', 'endcase', 'end', 'endfunction']
    lines += ['function automatic signed [9:0] score(input logic [127:0] state);', 'integer total;', 'begin', 'total=0;']
    for u,v,w in EDGES:
        lines.append(f'if(state[{u}] != state[{v}]) total=total+({w});')
    lines += ['score=total[9:0];', 'end', 'endfunction']
    lines += ['function automatic [31:0] probability(input logic [7:0] address);', 'begin', 'case(address)']
    lines += [f"8'd{i}: probability=32'h{int(w):08x};" for i,w in enumerate(LUT)]
    lines += ["default: probability=32'hffffffff;", 'endcase', 'end', 'endfunction']
    source=(ROOT/'solver_template.sv').read_text()
    for mode in ('baseline','epix'):
        dest=ROOT/'rtl'/mode
        dest.mkdir(parents=True,exist_ok=True)
        (dest/'graph_functions.svh').write_text('\n'.join(lines)+'\n')
        (dest/'solver.sv').write_text(source.replace('__EPIX_DEFAULT__',str(int(mode=='epix'))))
        (dest/'clock_gate_sim.sv').write_text('// Functional model of the source library ICG.\nmodule sky130_fd_sc_hd__dlclkp_1(input CLK,GATE,output GCLK);\nreg gate_latched;\nalways_latch if(!CLK) gate_latched=GATE;\nassign GCLK=CLK & gate_latched;\nendmodule\n')
    config=dict(schema_version=1,top='chimera_solver',clock_port='clk',source_icg=dict(cell='sky130_fd_sc_hd__dlclkp_1',clock_pin='CLK',enable_pin='GATE',output_pin='GCLK'),
        simulation=dict(driver='sim_main.cpp',prefix='Vchimera_solver',vector_suffix='.bin',compare_fields=['trial','success','final_success','sweeps','best_cut','final_cut','first_exact_sweep','local_words','visits','fired_cycles'],fresh_word_fields=['local_words'],setup_rng_words=256,
            boundary='Host setup supplies 128 fresh initialization words and 128 lane seed words. One RNG engine serves each bank of 32 stored spins, preserving separate stream states. All spins in a color commit after fresh requests finish. Search runs all 13118 sweeps, including after target success.'),
        input_evidence=['graph.json','software_spec.json','certificate.json'],
        rng_audit=dict(nets=[dict(name=f'lane[{i}].rng_state',width=32) for i in range(128)],expected_registers=4096,
                       engine_count=GRAPH['n']//32,stream_count=GRAPH['n'],stored_pbits_per_engine=32),modes={})
    for mode in ('baseline','epix'):
        config['modes'][mode]=dict(rtl=[f'rtl/{mode}/solver.sv'],include_dirs=[f'rtl/{mode}'],defines=dict(EPIX_MODE=int(mode=='epix')),expected_icg_count=256)
    config['rng_sharing']=dict(stored_variables=GRAPH['n'],variables_per_engine=32,
        local_engines=GRAPH['n']//32,stream_states=GRAPH['n'],auxiliary_engines=0,
        words_per_engine_per_cycle=1,mapping='contiguous groups of 32 variables',kind='banked')
    (ROOT/'asic.json').write_text(json.dumps(config,indent=2)+'\n')
if __name__=='__main__': generate()
